// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vectorify.Api.Data;

#nullable disable

namespace Vectorify.Api.Migrations
{
    [DbContext(typeof(VectorizationDbContext))]
    [Migration("20261003230452_AddDocumentVersionIdempotencyKey")]
    partial class AddDocumentVersionIdempotencyKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vectorify.Api.Data.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("Vectorify.Api.Data.DocumentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("HeightMm")
                        .HasColumnType("double precision");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SvgAssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VectorDocumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ViewBox")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("WidthMm")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("\"IdempotencyKey\" IS NOT NULL");

                    b.HasIndex("SvgAssetId");

                    b.HasIndex("VectorDocumentId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("document_versions", (string)null);
                });

            modelBuilder.Entity("Vectorify.Api.Data.Layer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ColorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean");

                    b.Property<string>("ManufacturingOperation")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("PathCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SvgAssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("SvgAssetId");

                    b.HasIndex("VersionId");

                    b.HasIndex("VersionId", "GroupId")
                        .IsUnique();

                    b.ToTable("layers", (string)null);
                });

            modelBuilder.Entity("Vectorify.Api.Data.PaletteColor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Coverage")
                        .HasColumnType("double precision");

                    b.Property<string>("Hex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBackground")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VersionId");

                    b.ToTable("palette_colors", (string)null);
                });

            modelBuilder.Entity("Vectorify.Api.Data.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ThumbnailAssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CurrentVersionId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ThumbnailAssetId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Vectorify.Api.Data.SchemaProbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("schema_probes", (string)null);
                });

            modelBuilder.Entity("Vectorify.Api.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("ExternalIdentityId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Vectorify.Api.Data.VectorDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("vector_documents", (string)null);
                });

            modelBuilder.Entity("Vectorify.Api.Data.Asset", b =>
                {
                    b.HasOne("Vectorify.Api.Data.Project", "Project")
                        .WithMany("Assets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Vectorify.Api.Data.DocumentVersion", b =>
                {
                    b.HasOne("Vectorify.Api.Data.Asset", "SvgAsset")
                        .WithMany()
                        .HasForeignKey("SvgAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vectorify.Api.Data.VectorDocument", "VectorDocument")
                        .WithMany("Versions")
                        .HasForeignKey("VectorDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SvgAsset");

                    b.Navigation("VectorDocument");
                });

            modelBuilder.Entity("Vectorify.Api.Data.Layer", b =>
                {
                    b.HasOne("Vectorify.Api.Data.PaletteColor", "Color")
                        .WithMany("Layers")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vectorify.Api.Data.Asset", "SvgAsset")
                        .WithMany()
                        .HasForeignKey("SvgAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Vectorify.Api.Data.DocumentVersion", "Version")
                        .WithMany("Layers")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("SvgAsset");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Vectorify.Api.Data.PaletteColor", b =>
                {
                    b.HasOne("Vectorify.Api.Data.DocumentVersion", "Version")
                        .WithMany("PaletteColors")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Vectorify.Api.Data.Project", b =>
                {
                    b.HasOne("Vectorify.Api.Data.DocumentVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vectorify.Api.Data.User", "Owner")
                        .WithMany("Projects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vectorify.Api.Data.Asset", "ThumbnailAsset")
                        .WithMany()
                        .HasForeignKey("ThumbnailAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentVersion");

                    b.Navigation("Owner");

                    b.Navigation("ThumbnailAsset");
                });

            modelBuilder.Entity("Vectorify.Api.Data.VectorDocument", b =>
                {
                    b.HasOne("Vectorify.Api.Data.Project", "Project")
                        .WithMany("VectorDocuments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Vectorify.Api.Data.DocumentVersion", b =>
                {
                    b.Navigation("Layers");

                    b.Navigation("PaletteColors");
                });

            modelBuilder.Entity("Vectorify.Api.Data.PaletteColor", b =>
                {
                    b.Navigation("Layers");
                });

            modelBuilder.Entity("Vectorify.Api.Data.Project", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("VectorDocuments");
                });

            modelBuilder.Entity("Vectorify.Api.Data.User", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Vectorify.Api.Data.VectorDocument", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
